# Generated by Django 6.0.2 on 2026-02-03 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='expired_at',
            new_name='expires_at',
        ),
    ]
