# Generated by Django 4.2.9 on 2026-02-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_alter_shorturl_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='qr_code_generated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when QR code was generated', null=True),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='qr_code_image',
            field=models.ImageField(blank=True, help_text='Generated QR code image', null=True, upload_to='qr_codes/'),
        ),
    ]
